name: Build and Deploy Django Admin with Keyboard Shortcuts Demo Static Site

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number of django-admin-keyshortcuts"
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        if [ -n "${{ inputs.pr_number }}" ]; then
            echo "Installing from PR #${{ inputs.pr_number }}"
            pip install "git+https://github.com/khanxmetu/django-admin-keyshortcuts.git@refs/pull/${{ inputs.pr_number }}/head"
          else
            echo "Installing from main branch"
            pip install "git+https://github.com/khanxmetu/django-admin-keyshortcuts.git@main"
          fi
    - name: Run migrations
      run: |
        source venv/bin/activate
        python manage.py migrate

    - name: Start Django dev server in background
      run: |
        source venv/bin/activate
        if [ -n "${{ inputs.pr_number }}" ]; then
          export URL_PREFIX="django-admin-keyshortcuts-demo/pr${{ inputs.pr_number }}"
        fi
        python manage.py runserver 0.0.0.0:8000 &
        sleep 5

    - name: Run snapshot script
      run: |
        if [ -n "${{ inputs.pr_number }}" ]; then
          export URL_PREFIX="django-admin-keyshortcuts-demo/pr${{ inputs.pr_number }}"
        fi
        chmod +x ./snapshot/backup.sh
        ./snapshot/backup.sh  || true

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./snapshot_data/django-admin-keyshortcuts-demo/${{ inputs.pr_number != '' && format('pr{0}', inputs.pr_number) || 'main' }}
        destination_dir: ${{ inputs.pr_number != '' && format('pr{0}', inputs.pr_number) || 'main' }}